### ISSUE TITLE
New Alpaca Websocket Rules

### ISSUE THREAD

**Issue by connor-mcswain** [camelpac/alpaca-proxy-agent#6]
Hi @shlomikushchi, do you have any ideas about how this project might change with Alpaca's new data product update? Looks like the free plan will now be limited to 30 symbols. Do you think we could still use this proxy to open multiple connections on the free plan as long as we stuck with the 30 symbols?

Also, I wonder if the paid plan with unlimited symbols will now allow unlimited websocket connections. No worries if you're not sure, just figured I'd check.

**Comment by shlomikushchi** [comment]
Hi, so this project does not use the data streams as a source. it uses a clock and polling. 
that means that when you need data you do a rest call. 
so there will be no 30 symbol limit.
the historical data is 15 minute delayed, so that means for daily strategies it probably won't matter as much. but for minute strategies it probably will. 
But I will probably know more in the next few weeks

**Comment by shlomiku** [comment]
Hi @connor-mcswain , sorry for the previous response I got confused with a different project. 
This project of course needs to be updated with the latest api (when it will be released) and will work with what ever the free plan provides.
you will be able to work with the 30 symbols since there will only be one websocket registering to them (I haven't seen anything to make me question that so far)
about the unlimited websockets for paid account, I have no answer for that just yet.

**Comment by connor-mcswain** [comment]
@shlomikushchi thank you, appreciate the update!

**Comment by gomezdanielg** [comment]
Hi! Do you have any plans to update this project to work with the last API?

**Comment by camelpac** [comment]
Hi, this project was updated to work with data v2.
read the readme to learn more on how to use it.
